### ISSUE TITLE
Windows startup

### ISSUE THREAD

**Issue by FusionFTW** [ahodges9/LedFx#109]
Hi guys,

I would like LedFx to start automatically after the Windows startup. Is this possible?

I used to do that with the "old" Systematic-LED by not-matt by using the Windows task scheduler but I don't which file to start. 

It would be useful to know which python file is started with the command "ledfx --open-ui". For Systematic-LED you had to execute the "main.py".

**Comment by rohanmuz2** [comment]
I am also looking for solution but for Linux system

**Comment by rohanmuz2** [comment]
I am able to do this by doing below step in pi 
1)Create any file called rohan.sh
--Content of file 
`/home/pi/.local/bin/ledfx`

2)Call this file in rc.local
`sudo /home/pi/rohan.sh 2 > /etc/nohup.out &`

3)sudo reboot

Once PI comes online Ledfx is able to start sucessfully

**Please rember to do all the installation with root user else it will not work
'

**Comment by FusionFTW** [comment]
I worked out a solution:

1) Create a batch file with this code:
`@echo off
C:\Users\_username_\anaconda3\Scripts\activate ledfx && ledfx --open-ui`
You might need to change the environment if you gave it another name.

2) Start the batch file on startup by either putting it into the Startup folder (WIN+R --> shell:startup) or creating a new task in the windows task sheduler.
