### ISSUE TITLE
Error running ledfx

### ISSUE THREAD

**Issue by jedimasta446** [ahodges9/LedFx#11]
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\Preston\AppData\Roaming\.ledfx\config.yaml", line 3, column 5

install seemed to work fine, however getting this every time I try to run it.

**Comment by ahodges9** [comment]
Can you share your config.yaml?

**Comment by jedimasta446** [comment]
got it, thanks for the help in discord!
