### ISSUE TITLE
Power Effect

### ISSUE THREAD

**Issue by FusionFTW** [ahodges9/LedFx#116]
Would it be possible to include the "Power" effect from [https://github.com/not-matt/Systematic-LEDs](url)

It is comparable to the wavelength effect but it also shows the volume of the bass.

You can spot it in this video at 13:05 [https://www.youtube.com/watch?v=W4jaAgjfvG8](url).

It was always a great effect at partys.

**Comment by not-matt** [comment]
Done

**Comment by not-matt** [comment]
effect is in dev branch
