### ISSUE TITLE
Shairport as input device

### ISSUE THREAD

**Issue by jptrsn** [ahodges9/LedFx#119]
This project looks great. I've seen demos of it, and I'm really interested in getting it working with my home audio setup using forked-daapd and airplay receivers.

However, I'm a bit stuck. Because I'm running my audio system on an ubuntu server, I can't seem to figure out how to use the audio output as an input for ledfx. I have no interest in using a microphone as the audio input, since it wouldn't pick up the system audio in the basement and I'm not down there anyway.

I've had lots of luck installing shairport on linux to use the device(s) as remote audio outputs for my home audio. I've got many speakers around the house, and it would be really cool if I had an "LedFX" output that I could select as if it were another speaker.

Is there any way to set this up? I saw in one post that I would need to set up an audio loop-back, but I don't know if that would be appropriate, and if so, I don't know how to do it.

Thanks for any help!

**Comment by mousemat86** [comment]
Did you ever find a solution for this? I'm looking for the same thing ...

**Comment by jptrsn** [comment]
For a little while, I was running LedFX on its own Pi with shairport installed as well, using a USB sound card and a short patch cable to link output to input. However, the Pi 3b ended up a little too laggy for my preference.

I ended up configuring my host machine to use local audio hardware inputs and outputs, and I've got a cable linking the audio out to the line in. Not ideal, but it works for me.
