### ISSUE TITLE
Led strip simply won't display effects.

### ISSUE THREAD

**Issue by OnsetMods** [ahodges9/LedFx#133]
I have managed to fix every other issue I've had when building this project, except now that everything runs, the led strip simply won't light up at all. I know I have everything installed and set up correctly. I even ran a Wireshark capture to confirm that my ESP8266 was receiving the UDP packets and it was so it is not a networking issue. I have the data pin for the led strip connected to the Rx pin on my NodeMCU and in the Arduino sketch I have the LED_PIN set to 3 since that is what GPIO pin number is listed as the Rx pin in the NodeMCU v3 pinout. I just have no idea where to go from here. Any help would be appreciated. Thanks!

**Comment by OnsetMods** [comment]
EDIT: I should note that other programs run with this hardware set up have worked. Leds work outside of this program.

**Comment by bjornstevens** [comment]
What code/ software are you running on the esp? I am working with WLED and it didn't work for me via UDP either. I had to use the UDP port of Hyperion. (19446)

**Comment by OnsetMods** [comment]
Currently I am using the firmware from an updated version of the original Scotts's audio reactive leds. Could you link to the firmware you were able to use? Thanks

**Comment by bjornstevens** [comment]
Try following this tutorial if possible:
https://www.youtube.com/watch?v=ipSfQdfX4fE

Try to tell where you can't go further or what doesn't work.

Does the LedFx run without a problem (no huge errors in the command line)?

**Comment by OnsetMods** [comment]
@bjornstevens Yes, ledfx runs without problems mostly. Only issue I've seen on the command line is sometimes certain effects are configured correctly but not many. I will try that tutorial and let you know how it goes! I appreciate the help.

**Comment by bjornstevens** [comment]
> 
> 
> @bjornstevens Yes, ledfx runs without problems mostly. Only issue I've seen on the command line is sometimes certain effects are configured correctly but not many.

I also get those a lot, sometimes if you dont get it to work, try restarting LedFx (on linux just CTRL + C and then start the command again)

**Comment by OnsetMods** [comment]
@bjornstevens So I able to get WLED installed and working in both AP mode and on a wifi hotspot form my phone (Don't have access to regular network but I'm fine with that). I even got the reactive Ledfx to work through the wifi hotspot. I set up my esp using e1.31 in WLED and it worked that way. Have not gotten it to work using UDP yet. 
That being said, I encountered this problem twice: When display an effect or using the reactive effects in ledfx, the strip will randomly turn completely white. Even rebooting WLED and power cycling the strip and esp didn't fix it. Finally I was able to fix it somehow after reflashing the esp and letting the leds sit unplugged for a while. I am not sure but it almost seems like the incoming packets are overwhelming the esp or stop and the esp gets stuck telling the leds to be white. 

I did all this without Hyperion. Do you think using that could solve some issues? How did you get it to work with that? Thanks!

**Comment by OnsetMods** [comment]
Well I've been messing with them for a while now, have not been able to recreate that white error so idk. but of course now something else has come up lol. Whenever I am using the ledfx to control the lights, no matter what effect or single color is show, there is a third of the strip that goes to the opposite color of what i want outputted. it even changes to the opposite color at a specific pixel for moving effects. However, when I do moving effects or single colors in WLED, it works fine and the colors are correct. This tells me it is something in the ledfx code rather than a fault in my strip.

**Comment by bjornstevens** [comment]
>  However, when I do moving effects or single colors in WLED, it works fine and the colors are correct. This tells me it is something in the ledfx code rather than a fault in my strip.

I had the exact same issue, i then switched to UDP mode. (and the port i said before)




> @bjornstevens So I able to get WLED installed and working in both AP mode and on a wifi hotspot form my phone (Don't have access to regular network but I'm fine with that). I even got the reactive Ledfx to work through the wifi hotspot. I set up my esp using e1.31 in WLED and it worked that way. Have not gotten it to work using UDP yet.
> That being said, I encountered this problem twice: When display an effect or using the reactive effects in ledfx, the strip will randomly turn completely white. Even rebooting WLED and power cycling the strip and esp didn't fix it. Finally I was able to fix it somehow after reflashing the esp and letting the leds sit unplugged for a while. I am not sure but it almost seems like the incoming packets are overwhelming the esp or stop and the esp gets stuck telling the leds to be white.
> 
> I did all this without Hyperion. Do you think using that could solve some issues? How did you get it to work with that? Thanks!

I also had some stability issues, this might be due to LedFx being very heavy on the network. I have a network with IOT devices in it, while i was setting up a new ESP while LedFx was running on my 2 strips i just wouldn't get any IP-address on it. You can maybe try decreasing the reresh rate.

I have also been having some issues with LedFx just crashing after selecting an some effects. WLED then goes to its default preset effect and color. Sometimes refreshing browser after applying 1 thing works out the most stable.


For now i can't really tell a lot because i am still trying to figure LedFx out, but it works good enough for me right now :)

**Comment by OnsetMods** [comment]
@bjornstevens Alright thank you so much for your help! I have gotten it to be pretty stable now but I am going to try switching to UDP with Hyperion to see if it fixes the colors. Where do you suggest I get started with Hyperion? Last thing before I close this thread and get out of your hair: You may or may or not have any ideas for this but whenever the colors change (moving or switching solids) the lights seem to flicker a lot while updating. This happens in both wled and ledfx. I almost think it is a voltage issue, so maybe I will try to get a capacitor to smooth out the voltage.

**Comment by bjornstevens** [comment]
> @bjornstevens Alright thank you so much for your help! I have gotten it to be pretty stable now but I am going to try switching to UDP with Hyperion to see if it fixes the colors. Where do you suggest I get started with Hyperion? Last thing before I close this thread and get out of your hair: You may or may or not have any ideas for this but whenever the colors change (moving or switching solids) the lights seem to flicker a lot while updating. This happens in both wled and ledfx. I almost think it is a voltage issue, so maybe I will try to get a capacitor to smooth out the voltage.

Wai.. wait! I didn't mean u need to install hyperion, i just use the UDP pprt that WLED uses for hyperion.
Try adding a device in ledfx with udp port 19446 and the ip of the esp. That should work just fine. No weird colors at least, and still pretty smooth!

**Comment by bjornstevens** [comment]
> @bjornstevens Alright thank you so much for your help! I have gotten it to be pretty stable now but I am going to try switching to UDP with Hyperion to see if it fixes the colors. Where do you suggest I get started with Hyperion? Last thing before I close this thread and get out of your hair: You may or may or not have any ideas for this but whenever the colors change (moving or switching solids) the lights seem to flicker a lot while updating. This happens in both wled and ledfx. I almost think it is a voltage issue, so maybe I will try to get a capacitor to smooth out the voltage.

What kind of power supply and led strip are you using? Power supply's from china may have very unclean dc output

**Comment by bjornstevens** [comment]
![Screenshot_20200920-015851_Firefox](https://user-images.githubusercontent.com/23235234/93691396-e33af200-fae4-11ea-9687-58d4b5e5c961.jpg)

**Comment by OnsetMods** [comment]
@bjornstevens  Ohhh okay gotcha. Well that makes it much easier to change! I'll try that now. 

I am using a beefy Mean Well power supply so I think it should be good. I am realizing thought that I am running my esp powered from my laptop with usb so the grounds on the leds and esp are not connected. I will also try running the esp off my power supply with the grounds connected.

**Comment by bjornstevens** [comment]
> @bjornstevens Ohhh okay gotcha. Well that makes it much easier to change! I'll try that now.
> 
> I am using a beefy Mean Well power supply so I think it should be good. I am realizing thought that I am running my esp powered from my laptop with usb so the grounds on the leds and esp are not connected. I will also try running the esp off my power supply with the grounds connected.

Make sure the grounds are connected, the live wires dont need to be on the same line, but they can if it is like 5v

**Comment by OnsetMods** [comment]
Unfortunately UDP is very broken for me. I set the port in WLED and added a device in ledfx using port 19446 as suggested. It barely works. Most colors will not turn on when trying to apply any effect. I can always get singleColor blue to work for some reason but not singleColor red. Honestly at this point I have no idea.. WLED works perfectly. I even tried creating an entirely new conda environment and reinstalling ledfx with everything but its the same thing. Ledfx works if I use e1.31, but the color changing 2/3 of the way down the strip is still there.

**Comment by OnsetMods** [comment]
......... I cannot believe I did not see this before.... #114 

When adding a device with more than 170 pixels with e1.31, change Universe Size in Advanced Configuration from 512 to 510 and the color changing error will be fixed.... I have my strip completely working now. 

@bjornstevens  Thank you very much for your help! I'm going to close this thread and hopefully it help others in the future!

**Comment by bjornstevens** [comment]
Just wanted to say that your last comment helped me out why my 288 Led-strip didn't work. e1.31 is definetly faster than hyperion!

**Comment by OnsetMods** [comment]
Awesome! Glad to hear it helped. I was reading through a bunch of issues and came across it and was very happy to have everything working! I have 2 300 led strips for my entire room so here's hoping they all work once I get them hung.
