### ISSUE TITLE
Web interface don't working

### ISSUE THREAD

**Issue by maxime92hs** [ahodges9/LedFx#155]
After installation of ledfx, i execute _ledfx --open-ui_ but it does not work. I don't understand. I am in windows 10 with anaconda
![image](https://user-images.githubusercontent.com/62555870/98705829-6ad30d80-237e-11eb-8e45-4d94ebe842c4.png)

**Comment by Mattallmighty** [comment]
Hey mate,

Can I please point you to the readme on: https://github.com/ahodges9/LedFx/tree/dev & https://ledfx.readthedocs.io/en/docs/index.html
Can I ask you to try the LedFx Exe version 0.0.3: https://ledfx.app/download/

Your welcome to join the developers on LedFx Discord: https://discord.com/invite/wJ755dY

**Comment by maxime92hs** [comment]
thank you it's work, but now i can't add device in ledfx

**Comment by Mattallmighty** [comment]
Can you send a screenshot of what you are experiencing? 
Under device management, add device button, do you get a popup?

**Comment by maxime92hs** [comment]
In the config the ip was simply not 127.0.0.1
