### ISSUE TITLE
Config Loading/Creation

### ISSUE THREAD

**Issue by not-matt** [ahodges9/LedFx#3]
Two things.

in ledfxcontroller\devices\__init__.py", line 151, in create_from_config
    name = device_config.get('type'))
AttributeError: 'str' object has no attribute 'get'

Changed to:
    name = type(device_config))

Now error is:
ledfxcontroller\utils.py", line 196, in create
    name, self._cls.__name__.lower()))
AttributeError: Couldn't find '<class 'str'>' in the device registry

Which I imagine is linked to what you mentioned about the config file needing fixing.

**Comment by ahodges9** [comment]
name = device_config.get('type')) is correct. The issue here is the before devices was just are array. I moved it to be a dict with the key being the devices id. You need to update the config.yaml to be something like:

devices:
  test_device:
    type: e131
    name: Sample Device
    host: 192.168.1.100
    pixel_count: 100
    max_brightness: 0.25

**Comment by not-matt** [comment]
Works like a charm.
