### ISSUE TITLE
Effects not the same as the original

### ISSUE THREAD

**Issue by lpearl** [ahodges9/LedFx#36]
Hi,

First, just like to say this project is amazing! Good job! I'm just noticing the effects specifically the scroll effect is not the same as the original. The one by @not-matt (Systematic-LEDs) is a lot smoother and looks nicer. I know there are settings to tweak but I can't seem to perfect it. I tried his fork but the same problem persists.

Thanks in advance,

lpearl

**Comment by not-matt** [comment]
could you describe how exactly its smoother? i could fix it up real quick

**Comment by lpearl** [comment]
I will try my best to explain it. instead of creating pulses of light that go down the strip it creates a wave. In yours there gaps in the pules so you can differentiate the sounds. In this, all the lights are on and there are no gaps. Thanks for the response!

**Comment by lpearl** [comment]
@not-matt any updates?

**Comment by Yariv-h** [comment]
Same thing here.. @not-matt  your original effects was much better. this one looks totally different

**Comment by not-matt** [comment]
Done, dev branch. Sorry for delay!
