### ISSUE TITLE
Failed to building wheel for aubio

### ISSUE THREAD

**Issue by Edris89** [ahodges9/LedFx#38]
Getting the following error after trying to install pip install ledfx
Running windows 10 64 bit
Anaconda 32 bit

 Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
Installing collected packages: pywin32, pypiwin32, aubio, MarkupSafe, jinja2, aiohttp-jinja2, ledfx
  Found existing installation: pywin32 221
Cannot uninstall 'pywin32'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by YeonV** [comment]
1) https://visualstudio.microsoft.com/de/downloads/
2) Tools für Visual Studio 2019
3) Buildtools für Visual Studio 2019 -> Download

**Comment by ahodges9** [comment]
Did you follow the install instruction here: https://ahodges9.github.io/LedFx/quickstart.html

You shouldn't use pip to install the aubio and pywin32 dependencies unless you want to install a c compiler and build tools. Instead use "conda install aubio portaudio pywin32" then install LedFx via pip.

Reactivate if you are still having issues.

**Comment by atuline** [comment]
Regarding aubio . . . 

On a fresh install (and patched) copy of Windows 10, LedFX failed to install. I followed the install instructions to the letter at:  https://ahodges9.github.io/LedFx/quickstart.html

Maybe there are some undocumented pre-requisites that LedFX requires that are not in those install instructions.

YeonV, above, mentions 'Build Tools for Visual Studio 2019', but there appear to be a LOT of selections, and who knows which one (or more) to select. There's also no mention of Visual Studio in the above install instructions.

In the meantime, here's (a small part of) the error I received:

 Info: libaubio was not installed or built locally with waf, adding src/
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
  ----------------------------------------
  ERROR: Failed building wheel for aubio

I'll start looking into YeonV's suggestion, but thank goodness for VM Snapshot/Restore. This is also why I'm very careful prior to installing packages on my production desktop.
