### ISSUE TITLE
Visualization Stuck

### ISSUE THREAD

**Issue by 5eed** [ahodges9/LedFx#40]
This affects 0 volume inputs , e.g. from virtual audio devices (direct playback from audio output). Occured while routing audio with Volume Control from PulseAudio in Linux.

Affected Code in ledfx/effects/audio.py:
`self._volume = aubio.db_spl(self._raw_audio_sample)
self._volume_filter.update(self._volume)` - line 155-156

If you look up aubio.db_spl function [https://aubio.org/manual/latest/py_utils.html](url), it is calculating the Sound Pressure Level by using log - resulting in **-inf**, if 0 input volume is provided, which is then used to update the volume_filter 

Once -inf is applied to ExpFilter Implementation of Scott Lawson it will keep this value, even if volume rises again after an 0 volume intput (song change, ...) -> disabling all further audio processing, since -inf is always smaller than the min_volume (default -70)

`if self._volume_filter.value > self._config['min_volume']: #process audio`

Possible Solution:
Add a check between lines 155 to 156:
` if  self._volume < self._config['min_volume']: 
 self._volume = -0.1 # set it to other value than -inf`

**Comment by richyxi** [comment]
Hi men, does it work for you?

**Comment by 5eed** [comment]
You mean the visualization in general or the suggested fix? - Works both for me

**Comment by richyxi** [comment]
Cool, I need to try this!

**Comment by spattinson** [comment]
This fixes my issue of getting no output at all on any of the audio reactive effects apart from gradient and one other. Thanks

**Comment by Zafrilla227** [comment]
I added that line of code, however I'm still facing the same issues of sound effects not being displayed.
The effects "pitchSpectrum" and "beat" don't work. However, setting the frequency range of the effect "beat" to brilliance makes it work, but it is unrelated to any sound of the PC, it is just a loop of colors.
Any healp is appreciated.

**Comment by ahodges9** [comment]
Thanks! Fixed in the dev branch should be integrating dev into master soon
