### ISSUE TITLE
pip install ledFX fails

### ISSUE THREAD

**Issue by microfx** [ahodges9/LedFx#41]
Hey! 

When trying to install ledFX I get following error: 

~/LedFx$ pip install ledfx
Collecting ledfx
  Could not find a version that satisfies the requirement ledfx (from versions: )
No matching distribution found for ledfx

Any idea?

**Comment by richyxi** [comment]
Python3 PIP install ledfx, can you try it

**Comment by microfx** [comment]
pip3 install ledfx
Collecting ledfx
  Could not find a version that satisfies the requirement ledfx (from versions: )
No matching distribution found for ledfx


python3 pip install ledfx
python3: can't open file 'pip': [Errno 2] No such file or directory

unfortunately the same...

**Comment by richyxi** [comment]
That's is telling you that you need to install pip package manager on your
python3 environment, python3.6 should work

**Comment by microfx** [comment]
python3.5 -m pip install ledfx
Collecting ledfx
  Could not find a version that satisfies the requirement ledfx (from versions: )
No matching distribution found for ledfx

I have no clue what I is wrong here - I have it installed I think. Always this version hell everywhere.

**Comment by richyxi** [comment]
You need python 3.6 or 3.7 not 3.5

**Comment by microfx** [comment]
thanks a lot! fixed it :)

**Comment by richyxi** [comment]
U welcome sir
