### ISSUE TITLE
pip install ledfx [WinError 87]

### ISSUE THREAD

**Issue by BlueheIix** [ahodges9/LedFx#42]
Hi

I followed the instructions with a fresh install of Anaconda on Windows till `pip install ledfx`.

Terminal spits out the followin:

> (ledfx) C:\Users\admin>pip install ledfx
> 
> Collecting ledfx
>   Using cached https://files.pythonhosted.org/packages/49/c6/d4d2e0faa94b43b983ec4185094ea0f0176ae117037528a3a58a504e5aa8/ledfx-0.3-py3-none-any.whl
> 
> Collecting pypiwin32>=223; platform_system == "Windows" (from ledfx)
>   Downloading https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
> 
> Collecting pyaudio>=0.2.11 (from ledfx)
>   Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
>     ERROR: Error [WinError 87] The parameter is incorrect while executing command python setup.py egg_info
> 
> ERROR: Could not install packages due to an EnvironmentError: [WinError 87] The parameter is incorrect

Googled for solutions but didn't finde anythin usefull. I'm quite new to python.

Using python 3.7.3, setuptools 41.0.1

Any help is appreciated.

**Comment by Vayain** [comment]
Hi, 
did you use python=3.6?

- create --name ledfx **python=3.6** 
- conda activate ledfx 
- conda config --add channels conda-forge 
- conda install aubio portaudio pywin32 
- pip install ledfx 
- ledfx --open-ui
