### ISSUE TITLE
Access the GUI from another PC on the lan?

### ISSUE THREAD

**Issue by mythral0** [ahodges9/LedFx#48]
Hi, really cool project.
I've completed installation on Debiun 10, when I start it, it starts the web server, but on address 127.0.0.1, how do I get it to bind to a different interface?

**Comment by mythral0** [comment]
Apologies, I've figured it out.

**Comment by sladaar** [comment]
sorry, how did you manage to access? i tried the ip:8888 but doesn't work!
Thanks!

**Comment by Tim-Dixon** [comment]
@sladaar when you run the command `ledfx` or `ledfx --open-ui` notice the default is to only host the webserver locally. i.e `127.0.0.1:8888`. If you notice as well, the output of the command shows where the config file is loaded from, for me it was `/home/pi/.ledfx`. Open that file in your preferred text editor `sudo nano /home/pi/.ledfx/config.yaml`, and change the host address to ether your IP or `0.0.0.0`, save and re-run the `ledfx`. You can now access the web dashboard from other devices on your LAN.

**Comment by sladaar** [comment]
many many thanks @Tim-Dixon , it works flawlessly and now i can control through the web interface in my domotic environment! 
Great!
Have a nice day!

**Comment by wessi86** [comment]
I've got the same issue. I added 
`host: 0.0.0.0`
to the confic.yaml, but it is still starting  the webinterface at http://127.0.1.1:8888.

**Comment by douglasbaptistasenai** [comment]
Also here. I put the host, changed the port and still does not load the web interface.

http://127.0.1.1:8383/
http://127.0.0.1:8383/
http://localhost:8383/

Started webinterface at http://127.0.1.1:8383/

**Comment by XelandOne** [comment]
I´ve got it working by using the devices IP instead of 0.0.0.0:
dev_mode: false
devices: {}
max_workers: 10
port: 8383
presents: {}
host: 192.168.0.107

**Comment by Tim-Dixon** [comment]
@douglasbaptistasenai did you try `host: 0.0.0.0` or `host: your-ipv4 (i.e: 192.168.1.10)`? The 127 is your localhost internal network and running anything on that subnet will only be available from that device. Putting it on 0.0.0.0 or your host's LAN IP opens up the port, 8383 in your case, to other devices on your LAN from your host's IP.

**Comment by ZickyZacky** [comment]
Hallo, ich versuche die IP des Host zu ändern, bekomme es aber leider nicht zu laufen. Ich habe die neueste Windowsinstallation 2.0.106.

**Comment by ZickyZacky** [comment]
Hello, I'm trying to change the IP of the host, but unfortunately I can't get it to work. I have the latest Windows installation 2.0.106.
