### ISSUE TITLE
cannot install due to 'PyYAML' please help

### ISSUE THREAD

**Issue by prankousky** [ahodges9/LedFx#56]
Hi everybody,

I just heard about this project and it sounds super fun! Unfortunately, I cannot install it. When I run `(sudo) pip install ledfx`, it will collect multiple requirements (and/or check whether they have already been satisfied), then stop with this error

```
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.8/site-packages (from jinja2>=2.7->aiohttp-jinja2==1.0.0->ledfx) (1.1.1)
Installing collected packages: voluptuous, pyyaml, sacn, multidict, yarl, async-timeout, aiohttp, pyaudio, aubio, aiohttp-jinja2, ledfx
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Apparently, `PyYAML 5.1.2` is already installed on my system; it has been installed by `distutils` and therefore I am not comfortable manually trying to uninstall it so that pip can start fresh. However, since it is already installed, why should it be uninstalled, anyway?

I am running `Arch Linux 5.3.11 x86_64` on an `Intel NUC`. Usually don't have problems with pip at all.

What can I do to fix this? Thank you for your solutions :)

**Comment by ahodges9** [comment]
Should be fixed with the latest LedFx v0.6. Try upgrading and reactivate if you have any issues.
