### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by epiller** [ahodges9/LedFx#63]
Could some good soul port this to MacOS? I've tried installing using the Linux installation docs but to no avail.

**Comment by ahodges9** [comment]
What issues are you having using the Linux instructions?

**Comment by epiller** [comment]
Couldn't find portaudio19-dev, but only portaudio, which I installed using 'brew cask' and after that I installed ledfx but after installing, even though it opened up the web UI, it doesn't seem to pick up audio or connect to LEDs either. I've been using Systematic-LEDs for a year or two without issues on Windows though.
Care to help? I can provide all the info necessary if needed.

**Comment by ahodges9** [comment]
You will likely need to go in and configure the audio device from the settings page. Would need more info about your LED setup to answer anything about that

**Comment by THATDONFC** [comment]
I'm running LedFX on my mac with no issues. I installed portaudio via brew install. The interface worked with the internal mic off the bat. Took some configuring to get the audio playing on the mac to get routed through LedFX. I installed the [BlackHole Driver](https://github.com/ExistentialAudio/BlackHole). This gave me the ability to select the blackhole driver as the source and all audio was routed through LedFX.

**Comment by epiller** [comment]
@ahodges9 It seems it was a mistake on my part. I messed up the firmware somewhere along the way. @THATDONFC That's exactly what I needed! I'm still fiddling with settings of BlackHole. Other than setting the BlackHole as default input, is there any possibility for telling LedFX to use the BlackHole as default input while all other apps use the microphone for input?

**Comment by epiller** [comment]
@ahodges9 I see that the latest version on master is 0.7 while only 0.3 is available via `pip3 install ledfx`. Any plans on updating the pip package?

**Comment by THATDONFC** [comment]
@epiller I select blackhole as the audio source in the ledfx ui. I haven’t tried using the internal mic while running ledfx. But I am not changing the input in the macOS settings so I would assume it should work that way.

**Comment by epiller** [comment]
@THATDONFC Hmm, I can't get my pip3 to download ledfx 0.7 for some reason, but only 0.3 (it sees it it as latest version for some reason). Since I can only install 0.3, I don't have the option to set inputs 😄

**Comment by THATDONFC** [comment]
There should be a way to upgrade. If not, you could backup your config.yaml in /.ledfx and remove/reinstall. Should install the latest version.

**Comment by epiller** [comment]
Finally made it. Had some path issues and a residue ledfx binary in /usr/local/bin that was called instead of the newer one. Works like a charm now, thank you very much!
P.S. Wish there was a way to enable setting volume when using the BlackHole audio output :)

**Comment by THATDONFC** [comment]
AFAIK the only way to adjust the system volume is to do it before you set the input. For some reason macOS won’t let you change the volume while using the blackhole driver. I just set the volume to max before connecting and adjust the volume on my desk speakers.

**Comment by epiller** [comment]
Honestly hate that decision so much, especially when connecting to HDMI output devices. 
Quick off-topic question: Can you set any of the variables on the ledfx web interface under 1? I can't seem to enter 0 as the first number.

**Comment by THATDONFC** [comment]
Type 1.5 and replace the 1 with a 0. Not sure why the web interface does that but it won't let you input a 0 by itself.
