### ISSUE TITLE
LedFx with Strip on Rasp3B GPIO

### ISSUE THREAD

**Issue by dogo77** [ahodges9/LedFx#76]
Hi.
I have an LED Strip directly connected to an Raspberry pi 3b Pin 18(GPIO5), controlled via
Scott’s audio-reactive-led-strip. working good.
Now i wanted to try LedFx, got the software running on the Raspberry but 
have Problems to get the LEDs lit.

As writen in the wiki i did
- Add the device as a UDP
- Click ‘Additional Properties’ and check ‘Include Indexes’

but what to enter for UDP-Port? and hostname?
entering the IP of the Raspberry  and some random udp port does not lead to success.

Any hints? Thanks!

**Comment by not-matt** [comment]
UDP port is either 7777 or 7778, you can find it in the Arduino file.

**Comment by dogo77** [comment]
Tried ports 7777 and 7778, still no success.
Also, i did not find any Arduino file, but that may be because i'm on Pi?
Or did i missunderstand everything and LedFx can not work like in this scheme?
[https://github.com/scottlawsonbc/audio-reactive-led-strip/blob/master/images/block-diagram.png](url)

**Comment by not-matt** [comment]
Ah apologies I hadn't read your problem fully. I thought you were using a
wireless Pi - ESP - LEDs setup.

As far as I know there's no standalone pi support for the setup you have
described;  Ledfx is designed to control wireless strips.

I could add in this support as it's pretty straightforward but I'm not sure
if it fits the scope of this project.

I'd recommend using a wireless setup as it allows you to connect multiple
strips. ESP8266s are dirt cheap! You could use the Pi as a headless
controller, and access Ledfx through any browser on the network.

Eg
Phone browser (http://[pi-IP-address]:8888]) for control interface
⬇️
Pi running ledfx
⬇️
Any number of led strips

**Comment by dogo77** [comment]
thanks for your quick answer which clarifies things a bit :)

I still dont fully understand that middle part of your flowchart.
How do i connect the ESP8266 to the strip? I don't need an arduino for each strip, do i?
Sorry for these nooby questions, but i didn't find answers in the wiki. Do you have a pic of such an setup?

what i finally want to achive is the following:
I  have a DJ stand with an LED-Strip facing crowd.
From DJ controller i go > booth out to an > USB-Soundcard on Raspberry running > Scotts audio-reactive-led-strip.

**Comment by not-matt** [comment]
Ah I see, in that case I'd run ledfx on the laptop, no need for a raspberry
pi. As long as the ESPs are on the same network as the laptop it should
work. Maybe configure them so they connect to a hotspot running on the
laptop - I used to do this.

**Comment by not-matt** [comment]
example setup 
https://imgur.com/z7eMCpZ

**Comment by dogo77** [comment]
thanks a LOT! that made it clear.
I now have LedFx runing on the DJ-Laptop, have the controllers audio card as input and see the lines dancing in the webinterface :)

Is a »NodeMCU Lua Lolin V3 Module ESP8266 ESP-12E« the right thing to buy?

**Comment by not-matt** [comment]
Grand, glad I could help.
I'm actually looking into buying small driver boards to allow direct usb
connection to the end of the led strip. Setting up esp connections over
WiFi when you're about to DJ is a pain, I've been there! With these, it
would be a case of soldering the usb connection to the led strip, then plug
and play, no esp tinkering.

**Comment by dogo77** [comment]
That sounds awesome!
But i guess thats pre alpha, isn't it? ;)
For now i'll give it a try with the Module mentioned above.
And thanks for leting me missuse the issue tracker as support forum… :)

**Comment by not-matt** [comment]
Pleasure, best of luck! Consider joining the Discord server for support in future.

**Comment by dogo77** [comment]
sosorry for reopening…but after searching all night long i still can't find that discord server address. mind sending me an invite?
