### ISSUE TITLE
issue raspberry pi

### ISSUE THREAD

**Issue by raymiec** [ahodges9/LedFx#9]
On the latest raspbian stretch i get the following error after install 

Finished processing dependencies for ledfxcontroller==0.1.0a0
root@raspberrypi:/home/pi/ledfx# ledfx --open-ui
Traceback (most recent call last):
  File "/usr/local/bin/ledfx", line 11, in <module>
    load_entry_point('ledfxcontroller==0.1.0a0', 'console_scripts', 'ledfx')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/ledfxcontroller-0.1.0a0-py3.5.egg/ledfxcontroller/__main__.py", line 26, in <module>
    from ledfxcontroller.core import LedFxController
  File "/usr/local/lib/python3.5/dist-packages/ledfxcontroller-0.1.0a0-py3.5.egg/ledfxcontroller/core.py", line 11, in <module>
    from ledfxcontroller.http import LedFxControllerHTTP
  File "/usr/local/lib/python3.5/dist-packages/ledfxcontroller-0.1.0a0-py3.5.egg/ledfxcontroller/http.py", line 7, in <module>
    from ledfxcontroller.api import RestApi
  File "/usr/local/lib/python3.5/dist-packages/ledfxcontroller-0.1.0a0-py3.5.egg/ledfxcontroller/api/__init__.py", line 28, in <module>
    class RestEndpoint(BaseRegistry):
  File "/usr/local/lib/python3.5/dist-packages/ledfxcontroller-0.1.0a0-py3.5.egg/ledfxcontroller/utils.py", line 92, in no_registration
    del cls._registry[name]
AttributeError: type object 'RestEndpoint' has no attribute '_registry'

**Comment by ahodges9** [comment]
You will need python 3.6 I use __init_subclass__ which requires it.

**Comment by raymiec** [comment]
nice one will try that now,  Do you have a raspberry pi to develop / test on ?    if not where in the world do you live?

**Comment by ahodges9** [comment]
I am not focused on Raspberry Pi yet. I am making design decisions to ensure it feasible to run on one, but I expect there are going to be some hurdles. This is not even in alpha yet, so expect to encounter hurdles.

**Comment by raymiec** [comment]
If you want one and it's feasible for me to send you one i can or send you some cash to buy one. 

The pi is the way forward for this :) ultimately the aim would be it running on a pi zero! But i'm happy to support financially / testing  for ultimate compatibility.

**Comment by ahodges9** [comment]
That is something outside my control for the most part. Looks like you are failing to compile the scipy module. I would try to update all your packages and see if that helps:
sudo apt-get update
sudo apt-get upgrade

If not I would check to see if there are any special requirements for raspberry pi to install scipy

**Comment by raymiec** [comment]
I had another go, installed some dev libs etc.

THis is where i get to now pi@raspberrypi:~/ledfx $ sudo python3.6 setup.py install
running install
running bdist_egg
running egg_info
writing ledfxcontroller.egg-info/PKG-INFO
writing dependency_links to ledfxcontroller.egg-info/dependency_links.txt
writing entry points to ledfxcontroller.egg-info/entry_points.txt
writing requirements to ledfxcontroller.egg-info/requires.txt
writing top-level names to ledfxcontroller.egg-info/top_level.txt
reading manifest file 'ledfxcontroller.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ledfxcontroller.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ledfxcontroller.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ledfxcontroller-0.1.0a0-py3.6.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing ledfxcontroller-0.1.0a0-py3.6.egg
Removing /usr/local/lib/python3.6/site-packages/ledfxcontroller-0.1.0a0-py3.6.egg
Copying ledfxcontroller-0.1.0a0-py3.6.egg to /usr/local/lib/python3.6/site-packages
ledfxcontroller 0.1.0a0 is already the active version in easy-install.pth
Installing ledfx script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/ledfxcontroller-0.1.0a0-py3.6.egg
Processing dependencies for ledfxcontroller==0.1.0a0
Searching for PyYAML==3.13
Best match: PyYAML 3.13
Processing PyYAML-3.13-py3.6-linux-armv7l.egg
PyYAML 3.13 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/PyYAML-3.13-py3.6-linux-armv7l.egg
Searching for aiohttp-jinja2==1.0.0
Best match: aiohttp-jinja2 1.0.0
Processing aiohttp_jinja2-1.0.0-py3.6.egg
aiohttp-jinja2 1.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/aiohttp_jinja2-1.0.0-py3.6.egg
Searching for aiohttp==3.3.2
Best match: aiohttp 3.3.2
Processing aiohttp-3.3.2-py3.6-linux-armv7l.egg
aiohttp 3.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/aiohttp-3.3.2-py3.6-linux-armv7l.egg
Searching for sacn==1.3
Best match: sacn 1.3
Processing sacn-1.3-py3.6.egg
sacn 1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/sacn-1.3-py3.6.egg
Searching for PyAudio==0.2.11
Best match: PyAudio 0.2.11
Processing PyAudio-0.2.11-py3.6-linux-armv7l.egg
PyAudio 0.2.11 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/PyAudio-0.2.11-py3.6-linux-armv7l.egg
Searching for voluptuous==0.11.1
Best match: voluptuous 0.11.1
Adding voluptuous 0.11.1 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for scipy==1.1.0
Best match: scipy 1.1.0
Processing scipy-1.1.0-py3.6-linux-armv7l.egg
scipy 1.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-armv7l.egg
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for Jinja2==2.10
Best match: Jinja2 2.10
Adding Jinja2 2.10 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for idna-ssl==1.1.0
Best match: idna-ssl 1.1.0
Adding idna-ssl 1.1.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for yarl==1.2.6
Best match: yarl 1.2.6
Adding yarl 1.2.6 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for async-timeout==3.0.0
Best match: async-timeout 3.0.0
Adding async-timeout 3.0.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for multidict==4.3.1
Best match: multidict 4.3.1
Adding multidict 4.3.1 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages
Searching for attrs==18.1.0
Best match: attrs 18.1.0
Adding attrs 18.1.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for MarkupSafe==1.0
Best match: MarkupSafe 1.0
Adding MarkupSafe 1.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for idna==2.7
Best match: idna 2.7
Adding idna 2.7 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Finished processing dependencies for ledfxcontroller==0.1.0a0
pi@raspberrypi:~/ledfx $ sudo ledfx --open-ui
Traceback (most recent call last):
  File "/usr/local/bin/ledfx", line 11, in <module>
    load_entry_point('ledfxcontroller==0.1.0a0', 'console_scripts', 'ledfx')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'ledfxcontroller'
pi@raspberrypi:~/ledfx $ ledfx --open-ui
Traceback (most recent call last):
  File "/usr/local/bin/ledfx", line 11, in <module>
    load_entry_point('ledfxcontroller==0.1.0a0', 'console_scripts', 'ledfx')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'ledfxcontroller'
pi@raspberrypi:~/ledfx $

**Comment by raymiec** [comment]
```
pi@raspberrypi:~/ledfx $ sudo pip3.6 install --verbose -r requirements.txt
Requirement already satisfied: numpy==1.13.3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: voluptuous==0.11.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pyaudio==0.2.11 in /usr/local/lib/python3.6/site-packages/PyAudio-0.2.11-py3.6-linux-armv7l.egg (from -r requirements.txt (line 6))
Requirement already satisfied: sacn==1.3 in /usr/local/lib/python3.6/site-packages/sacn-1.3-py3.6.egg (from -r requirements.txt (line 7))
Requirement already satisfied: aiohttp==3.3.2 in /usr/local/lib/python3.6/site-packages/aiohttp-3.3.2-py3.6-linux-armv7l.egg (from -r requirements.txt (line 8))
Requirement already satisfied: aiohttp_jinja2==1.0.0 in /usr/local/lib/python3.6/site-packages/aiohttp_jinja2-1.0.0-py3.6.egg (from -r requirements.txt (line 9))
Requirement already satisfied: pyyaml<4,>=3.11 in /usr/local/lib/python3.6/site-packages/PyYAML-3.13-py3.6-linux-armv7l.egg (from -r requirements.txt (line 10))
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: async_timeout<4.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: idna-ssl>=1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: jinja2>=2.7 in /usr/local/lib/python3.6/site-packages (from aiohttp_jinja2==1.0.0->-r requirements.txt (line 9))
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.3.2->-r requirements.txt (line 8))
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from jinja2>=2.7->aiohttp_jinja2==1.0.0->-r requirements.txt (line 9))
```

**Comment by auditdata** [comment]
This what I did to get it working on Raspberry Pi 3B and Pi 4
Open a Terminal window.

```
wget https://github.com/jjhelmus/berryconda/releases/download/v2.0.0/Berryconda3-2.0.0-Linux-armv7l.sh
chmod +x Berryconda3-2.0.0-Linux-armv7l.sh
sudo ./Berryconda3-2.0.0-Linux-armv7l.sh
```
NOTE need to change install location to
/home/pi/berryconda3/
Then
`sudo nano /home/pi/.bashrc`
NOTE need to add:
export PATH="/home/pi/berryconda3/bin:$PATH"
to the end of the file and save
Then
```
sudo reboot -h now
conda create -n ledfx  
source activate ledfx
sudo chown pi:pi -R /home/pi/berryconda3/
pip install Cython
sudo apt-get install portaudio19-dev
pip install ledfx
```
Before I could get the audio to work I had to find out which Device number the USB microphone was on.
I used 
`sudo python3.7 -m pip install sounddevice`
and then ran
`python3.7 -m sounddevice`
Which gave 
0 bcm2835 ALSA: IEC958/HDMI (hw:0,1), ALSA (0 in, 8 out)
1 bcm2835 ALSA: IEC958/HDMI1 (hw:0,2), ALSA (0 in, 8 out)
2 2 Channel USB Audio: - (hw:1,0), ALSA (2 in, 2 out)
3 dmix, ALSA (0 in, 2 out)

This let me know it was Device 2 so had to edit the yaml file in 
/home/pi/.ledfx
and add
```
audio
  device_index: 2
```
at the beginning of the file
To run LEDFX type
`ledfx --open-ui`
It will open the UI
The next time you want to use it you need activate the environment again with 

```
source activate ledfx
ledfx --open-ui
```
