### ISSUE TITLE
Half the ledstrip freezes after a couple of minutes

### ISSUE THREAD

**Issue by olkarls** [ahodges9/LedFx#96]
After a couple of minutes half the strip becomes unresponsive.

My strip has 300 leds and connected to a esphome and communicates via WLED. I use an 18A power supply and inject power at start, middle and end of the strip. 

Heres a video of the error: [https://youtu.be/AZkSZ5oacu0](https://youtu.be/AZkSZ5oacu0)

The device is using e131 has 510 as universe size setting.

What could be wrong here? Has anyone else experienced this?

Thank you

/ Ola

**Comment by uttaran18** [comment]
Its a WLED Issue. Just enable Ignore our of sequence packets in WLED sync settings.

**Comment by Peterabboud** [comment]
@uttaran18  do you mind clarfying this ? I have went to the sync settings and cannot seem to find this. I'm also having the same issue above. Many Thanks

**Comment by tegazoid** [comment]
I updated WLED to version 0.10.0 and that seemed to have fixed it for me.
And the Ignore our of sequence packets option got added in that version (i think)

**Comment by Peterabboud** [comment]
I just saw that there was an update! that's awesome thanks man :)

**Comment by olkarls** [comment]
Sorry for the late reply, I switched to UDP before your answer and everything works as expected.
